# Generated by Django 3.2.11 on 2022-01-08 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=256, null=True)),
                ('completed', models.BooleanField(blank=True, default=False)),
                ('url', models.CharField(blank=True, max_length=256, null=True)),
                ('order', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
